### ISSUE TITLE
Document suggestion...

### ISSUE THREAD

**Issue by wtanksleyjr** [gfxmonk/gup#7]
I'm having a hard time using the documentation to figure out gup, but I like what I see of the project's basic setup.

The document has a section like the following:

>Obviously, that small example doesn't tell you everything you need to know, but hopefully it gives you a basic idea of how gup works. Here are the full details:
>
>*The search path*
>
>When you run gup build/foo from /home/tim/proj, gup will look for direct build scripts, in this order:

It took me a while to figure this out, so maybe I'm just slow: but I think the problem with the document is that it tries to start with a discussion of search order, when the reader doesn't know what the gup command line is or what a direct build script is.

How about:

>*gup invocation*
>  Gup has many command line options, but when you're using it interactively and for most of your use in scripts, you'll usually be typing a command that looks like 'gup targetname'. You will use 'gup -u targetname' if you want gup to skip running the build if the target's already up to date; otherwise, gup will run the script to build the named target. Gup has a very particular set of skills; it will find the target anywhere in the current project (see *the search path* for more details on where gup will stop looking). A more advanced invocation is 'gup path/targetname', which will allow you to have multiple targets with the same name in differently-named folders (um, I'm not sure about this, what's the real reason?).
>[more...]

>*gup build scripts*
> The simplest way to think of a build script is a script that simply builds a single target. This is called a "direct build script", and all direct build scripts are named "targetname.gup". If you've ever written a shell script to do a simple task, the same every time, you know the basics of writing a direct build script.
> Gup also supports a configuration file called an "indirect build script." Although direct build scripts are very simple, it's reasonably common to have very many small tasks that share common definitions like what many people put into a makefile. For this reason, or any others you may have, gup will read files named 'Gupfile' and expect to find these indirect build scripts.

Also, you warn against using bash, while not providing any examples aside from bash. I'd really like to see what something else would look like -- just enough to get me started.

**Comment by gfxmonk** [comment]
I wrote most of the README fairly early on, so yeah it's probably time to commit to some more concrete docs now that gup and its features seem more settled. Thanks for the suggestions, I'll try to roll these into some better docs soon :)

**Comment by gfxmonk** [comment]
I've just pushed a commit with a new `examples/` directory, plus some updates to the README incorporating your points above. If you're still keen, I'd appreciate any feedback on whether the examples make sense / help / are confusing :)

https://github.com/gfxmonk/gup/tree/master/examples

(closing this issue for now, but feel free to either reopen or create individual issues / PRs if you have suggestions)
